#!/bin/csh
#PBS -N test_calibration
#PBS -q omp
#PBS -l select=1:ncpus=8:mem=16g
#PBS -l walltime=01:00:00

source /usr/share/Modules/3.2.10/init/csh

# change to work directory
cd $PBS_O_WORKDIR


# export R_LIBS with the desired version of calibrar
setenv R_LIBS /home1/datawork/$USER/libs/R/lib

# Load modules (if available, choose versions working in parallel)
module load R/3.6.3-intel-cc-17.0.2.174

# Run with command line arguments
time Rscript calibrar_minimal.R --ncores=6 >>& mycalibration.log